[main]
font=Iosevka Medium:size=14
prompt=> 
icon-theme=Papirus-Dark
show-actions=no

# Dimensions
width=30
tabs=4
horizontal-pad=20
vertical-pad=20
inner-pad=15

border-radius=10
border-width=1

[colors]
background=120a08a0
text=8c734eff
match=b3976dff
selection=d3bd95ff
selection-text=120a08ff
border=b3976dff

[border]
width=1
radius=10
